PREFIX rdfs: <http://www.w3.org/2000/01/rdf-schema#>
PREFIX owl: <http://www.w3.org/2002/07/owl#>
PREFIX d3f: <http://d3fend.mitre.org/ontologies/d3fend.owl#>

CONSTRUCT {
# Alternate approach if want to create shadow instances
# that aren't puns, requires binds at bottom.
#    ?subject_class_inst a ?subject_class .
#    ?object_class_inst a ?object_class . 
#    ?subject_class_inst ?property ?object_class_inst .

     ?subject_class ?property ?object_class .

# Various DEBUGs
#    ?subject_class ?property ?top_class . # DEBUG 
#    ?restriction a owl:Restriction # DEBUG
#    ?subject_class rdfs:subClassOf ?top_class . # DEBUG
}
WHERE {
    ?subject_class rdfs:subClassOf+ ?top_class . # ?top_class stands in for owl:Thing
    # WTH robot!?; owl:Thing doesn't work here! # DELETE LINE AFTER DISCUSSION
    VALUES ?top_class { d3f:D3FENDThing d3f:ATTACKThing d3f:D3FENDAnalysisThing } .
    ?restriction a owl:Restriction .
    ?subject_class rdfs:subClassOf ?restriction .
    ?restriction owl:onProperty ?property . 
    ?restriction owl:someValuesFrom ?object_class .
    ?object_class rdfs:subClassOf+ ?another_top_class .
    VALUES ?another_top_class { d3f:D3FENDThing d3f:ATTACKThing d3f:D3FENDAnalysisThing } .
#    BIND ( CONCAT( STR(?subject_class), "_inst") as ?subject_class_inst)
#    BIND ( CONCAT( STR(?object_class), "_inst") as ?object_class_inst)
}
