PREFIX rdfs: <http://www.w3.org/2000/01/rdf-schema#>
PREFIX owl: <http://www.w3.org/2002/07/owl#>
PREFIX d3f: <http://d3fend.mitre.org/ontologies/d3fend.owl#>
PREFIX xsd: <http://www.w3.org/2001/XMLSchema#>

SELECT ?oldiri ?newiri
WHERE
{	
    ?oldiri rdfs:subClassOf* d3f:OffensiveTechnique .
    ?oldiri d3f:attack-id ?attack_id .
    BIND ("http://d3fend.mitre.org/ontologies/d3fend.owl#" AS ?ontology_prefix)
    BIND (iri(concat(?ontology_prefix, ?attack_id)) AS ?newiri)
}
