PREFIX rdfs: <http://www.w3.org/2000/01/rdf-schema#>
PREFIX owl: <http://www.w3.org/2002/07/owl#>
PREFIX d3f: <http://d3fend.mitre.org/ontologies/d3fend.owl#>

PREFIX rdfs: <http://www.w3.org/2000/01/rdf-schema#>
PREFIX owl: <http://www.w3.org/2002/07/owl#>
PREFIX d3f: <http://d3fend.mitre.org/ontologies/d3fend.owl#>

SELECT DISTINCT ?entity ?property ?packed_label
WHERE {
     VALUES ?top_class { d3f:ATTACKThing d3f:D3FENDThing d3f:D3FENDAnalysisThing }
     ?entity rdfs:subClassOf* ?top_class .
     BIND(rdfs:label AS ?property)
     ?entity ?property ?value .
     BIND(REPLACE(?value, " ", "") AS ?packed_label)
     FILTER NOT EXISTS {
        FILTER regex(str(?entity), concat(".*#", ?packed_label))
     }
     FILTER NOT EXISTS {
         ?tactic_technique rdfs:subClassOf d3f:OffensiveTechnique .
	 ?entity rdfs:subClassOf+ ?tactic_technique .
     }
}
