PREFIX rdfs: <http://www.w3.org/2000/01/rdf-schema#>
PREFIX owl: <http://www.w3.org/2002/07/owl#>
PREFIX d3f: <http://d3fend.mitre.org/ontologies/d3fend.owl#>

SELECT DISTINCT ?entity ?property ?value
WHERE {
      ?tactic_technique rdfs:subClassOf d3f:OffensiveTechnique .
      ?entity rdfs:subClassOf+ ?tactic_technique .
      BIND(d3f:attack-id AS ?property)
      FILTER NOT EXISTS { ?entity ?property ?value }
}
