PREFIX owl: <http://www.w3.org/2002/07/owl#>
PREFIX d3f: <http://d3fend.mitre.org/ontologies/d3fend.owl#>

SELECT ?version ?release_date ?triple_count
WHERE {
    {
        SELECT (COUNT(*) AS ?triple_count)
        WHERE {
            ?subject ?predicate ?object .
        }
    }
    OPTIONAL {
        <http://d3fend.mitre.org/ontologies/d3fend.owl> owl:versionInfo ?version .
    }
    OPTIONAL {
        <http://d3fend.mitre.org/ontologies/d3fend.owl> d3f:release-date ?release_date .
    }
}
