PREFIX rdfs: <http://www.w3.org/2000/01/rdf-schema#>
PREFIX owl: <http://www.w3.org/2002/07/owl#>
PREFIX d3f: <http://d3fend.mitre.org/ontologies/d3fend.owl#>

# Entity in violation is a property here!
SELECT DISTINCT ?entity ?property ?value
WHERE {
      VALUES ( ?super_annotation_entity) { # Annotation props:
      			                  (d3f:d3fend-annotation) }
      VALUES ( ?super_data_entity ) { # Data props:
      	     		              (d3f:d3fend-analysis-data-property)
				      (d3f:d3fend-artifact-data-property)
	       		              (d3f:d3fend-display-property)
	       		              (d3f:d3fend-kb-data-property)
	       		              (d3f:d3fend-analysis-object-property) }
      VALUES ( ?super_object_entity ) { # Object props:
      			               (d3f:d3fend-kb-object-property)
				       (d3f:may-be-associated-with) }
      ?annotation_entity rdfs:subPropertyOf* ?super_annotation_entity .
      ?data_entity rdfs:subPropertyOf* ?super_data_entity .
      ?object_entity rdfs:subPropertyOf* ?super_object_property .
      (UNION
	 ?annotation_entity
      BIND(d3f:definition AS ?property)
      FILTER NOT EXISTS{ ?entity ?property ?value . }
}
