PREFIX d3f: <http://d3fend.mitre.org/ontologies/d3fend.owl#>
PREFIX xsd: <http://www.w3.org/2001/XMLSchema#>

DELETE { ?s d3f:has-link ?string }
INSERT { ?s d3f:has-link ?any_uri }
WHERE {
   ?s d3f:has-link ?string . 
   FILTER(datatype(?string) = xsd:string)
   BIND(STRDT(?string, xsd:anyURI) as ?any_uri)
}
