PREFIX rdfs: <http://www.w3.org/2000/01/rdf-schema#>
PREFIX rdf: <http://www.w3.org/1999/02/22-rdf-syntax-ns#>
PREFIX owl: <http://www.w3.org/2002/07/owl#>
PREFIX d3f: <http://d3fend.mitre.org/ontologies/d3fend.owl#>

SELECT DISTINCT ?entity ?property ?value
WHERE {
      BIND(rdf:type AS ?property)
      ?entity ?property ?value .
      ?value rdfs:subClassOf* d3f:D3FENDAnalysisThing .
}
